name: "My CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  test_my_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Use the latest version

      - uses: actions/setup-node@v3  # Use the latest version
        with:
          node-version: '20.x'  # Use Node.js version 20

      - run: npm install          # Install dependencies using npm

      - run: npm run build        # Build the project

      - name: Run tests
        run: npm run test         # Run tests using npm
