name: "My CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  test_my_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Updated to the latest version

      - uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: '20.x'  # Use Node.js version 20
          cache: 'pnpm'         # Enable caching for pnpm

      - run: npm install -g pnpm  # Install pnpm globally

      - run: pnpm install          # Install dependencies using pnpm

      - run: pnpm run build        # Build the project

      - name: Run tests
        run: pnpm run test         # Run tests using pnpm
