name: "My CI"

on:
  push:
    branches: [ master ]
jobs:
  test_my_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - run: npm ci

      - run: npm run build

      - name: Run tests
        run: npm run test
