name: "My CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  test_my_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Use the latest version of the checkout action

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Set up Docker Buildx for multi-platform builds

      - name: Build Docker containers
        run: |
          docker-compose -f docker-compose.yml build  # Build the containers defined in your docker-compose file

      - name: Run tests
        run: |
          docker-compose -f docker-compose.yml up --abort-on-container-exit  # Start the containers and run tests
          
      - name: Clean up
        if: always()  # This step will run even if previous steps fail
        run: docker-compose -f docker-compose.yml down  # Stop and remove containers
