name: "My CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ main ]

jobs:
  test_my_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Use the latest version of the checkout action

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Install Docker Compose

      - name: Build Docker containers
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          PORT: 8080
          # Add more secrets as needed
        run: |
          docker-compose -f compose.yaml build  # Build the containers defined in your docker-compose file

      - name: Run tests
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          PORT: 8080
          # Add more secrets as needed
        run: |
          docker-compose -f compose.yaml up --abort-on-container-exit  # Start the containers and run tests
          
      - name: Clean up
        if: always()  # This step will run even if previous steps fail
        run: docker-compose -f compose.yaml down  # Stop and remove containers
