name: "My CI"

on:
  push:
    branches: [ master ]  # Change to 'main' if you intend to use 'main'
  pull_request:
    branches: [ master ]  # Change to 'main' if needed

jobs:
  test_my_code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # Use the latest version of the checkout action

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose  # Install Docker Compose

      - name: Prepare environment files
        run: |
          touch .env.database
          touch .env.prod
          echo POSTGRES_DB=example > .env.database
          echo POSTGRES_PASSWORD=password >> .env.database
          echo DATABASE_URL=postgres://postgres:password@db:5432/example > .env.prod
          echo PORT=8080 >> .env.prod
          echo DATABASE_PASSWORD=password >> .env.prod

      - name: Build Docker containers
        run: |
          docker-compose -f compose.yaml build  # Build the containers defined in your docker-compose file

      - name: Run tests
        run: |
          docker-compose -f compose.yaml up --abort-on-container-exit  # Start the containers and run tests

      - name: Clean up
        if: always()  # This step will run even if previous steps fail
        run: docker-compose -f compose.yaml down  # Stop and remove containers
