name: "My CI"

on:
  push:
    branches: [ master ]  # Change to 'main' if you intend to use 'main'
  pull_request:
    branches: [ master ]  # Change to 'main' if needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.REMOTE_SSH_KEY }}

      - name: Manually add SSH key with passphrase
        run: |
          echo "${{ secrets.SSH_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
            cd ${{ secrets.REMOTE_DIR }}
            git pull
            docker-compose -f compose.yaml build
            docker-compose -f compose.yaml up -d --remove-orphans
          EOF
